[package]
name = "maw"
version = "1.0.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
base64 = "0.22.1"
bpaf = { version = "0.9.23", features = ["derive"] }
serde_json = "1.0.149"
sha1 = "0.10.6"
tokio = { version = "1.49.0", features = ["full"] }
